### ISSUE TITLE
CiviCRM_API3_Exception: "DB Error: no such table"

### ISSUE THREAD

**Issue by magnolia61** [mattwire/civicrm-advanced-events#1]
When I enable this extension all seems fine, except when I go to Manage Events. Then a fatal error occurs with the following backtrace:

```
#0 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm_extensions/civicrm-advanced-events/advanced_events.php(269): civicrm_api3("EventTemplate", "get", (Array:3))
#1 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Utils/Hook.php(270): advanced_events_civicrm_pageRun(Object(CRM_Event_Page_ManageEvent))
#2 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(84): CRM_Utils_Hook->runHooks((Array:261), "civicrm_pageRun", 1, Object(CRM_Event_Page_ManageEvent), NULL, NULL, NULL, NULL, NULL)
#3 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(86): CRM_Utils_Hook_DrupalBase->invokeViaUF(1, Object(CRM_Event_Page_ManageEvent), NULL, NULL, NULL, NULL, NULL, "civicrm_pageRun")
#4 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(184): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_pageRun", Object(Civi\Core\CiviEventDispatcher))
#5 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:1), "hook_civicrm_pageRun", Object(Civi\Core\Event\GenericHookEvent))
#6 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("hook_civicrm_pageRun", Object(Civi\Core\Event\GenericHookEvent))
#7 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Utils/Hook.php(164): Civi\Core\CiviEventDispatcher->dispatch("hook_civicrm_pageRun", Object(Civi\Core\Event\GenericHookEvent))
#8 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Utils/Hook.php(795): CRM_Utils_Hook->invoke((Array:1), Object(CRM_Event_Page_ManageEvent), NULL, NULL, NULL, NULL, NULL, "civicrm_pageRun")
#9 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Core/Page.php(177): CRM_Utils_Hook::pageRun(Object(CRM_Event_Page_ManageEvent))
#10 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Event/Page/ManageEvent.php(283): CRM_Core_Page->run()
#11 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Event_Page_ManageEvent->run((Array:3), NULL)
#12 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:14))
#13 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#14 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#15 /var/www/vhosts/xyz/webroot/includes/menu.inc(527): civicrm_invoke("event", "manage")
#16 /var/www/vhosts/xyz/webroot/index.php(21): menu_execute_active_handler()
#17 {main}
```

**Comment by mattwire** [comment]
There should be a table `civicrm_event_template` created on install of the extension.  Looks like it may not have installed properly on your system?

**Comment by mattwire** [comment]
@magnolia61 Did you resolve this?

**Comment by magnolia61** [comment]
reinstalled and works ok now
